const fs = require('fs');

const file = 'src/ai/circuitChatAI.js';
let code = fs.readFileSync(file, 'utf8');

const t1 = `  let codeStr = "";
  if (codeIncludes.size > 0 || codeSetup.length > 0) {
    codeStr += \`\\n\`;
    codeIncludes.forEach(inc => codeStr += inc + '\\n');
    codeStr += \`\\nvoid setup() {\\n  Serial.begin(115200);\\n\`;
    codeSetup.forEach(s => codeStr += s + '\\n');
    codeStr += \`}\\n\\nvoid loop() {\\n  // Auto-generated by TinkerAI Offline Engine\\n}\\n\`;
    payload.code = codeStr;
  }`;

const t2 = t1.replace(/\n/g, '\r\n');

const r = `  let codeStr = "";
  if (codeIncludes.size > 0) {
    codeStr += \`\\n\`;
    codeIncludes.forEach(inc => codeStr += inc + '\\n');
  }
  codeStr += \`\\nvoid setup() {\\n  Serial.begin(115200);\\n\`;
  codeSetup.forEach(s => codeStr += s + '\\n');

  const mcuPinSetups = new Set();
  payload.wiring.forEach(w => {
    let mcuPin = null;
    let compId = null;
    if (w.toComp === 'mcu') { mcuPin = w.toPin; compId = w.fromComp.split('_')[0]; }
    else if (w.fromComp === 'mcu') { mcuPin = w.fromPin; compId = w.toComp.split('_')[0]; }
    
    if (mcuPin && !['GND','5V','3V3','3.3V','VIN','VCC'].includes(mcuPin) && !mcuPin.startsWith('A') && !isNaN(parseInt(mcuPin))) {
      let mode = 'OUTPUT';
      if (compId.includes('sensor') || compId.includes('button') || compId.includes('switch') || compId.includes('joystick') || compId.includes('ldr') || compId.includes('dht') || compId.includes('hx711') || compId.includes('encoder') || compId.includes('receiver') || compId.includes('keypad')) {
        mode = 'INPUT';
      }
      if (compId.includes('button') || compId.includes('switch')) {
        mode = 'INPUT_PULLUP';
      }
      mcuPinSetups.add(\`  pinMode(\${mcuPin}, \${mode}); // \${compId}\`);
    } else if (mcuPin && mcuPin.startsWith('A')) {
      mcuPinSetups.add(\`  pinMode(\${mcuPin}, INPUT); // \${compId}\`);
    }
  });

  mcuPinSetups.forEach(s => codeStr += s + '\\n');
  codeStr += \`}\\n\\nvoid loop() {\\n  // Auto-generated by TinkerAI Offline Engine\\n}\\n\`;
  payload.code = codeStr;`;

if (code.includes(t1)) {
    code = code.replace(t1, r);
    console.log("Patched LF");
} else if (code.includes(t2)) {
    code = code.replace(t2, r.replace(/\n/g, '\r\n'));
    console.log("Patched CRLF");
} else {
    console.error("Not found!");
    process.exit(1);
}

fs.writeFileSync(file, code, 'utf8');
