const fs = require('fs');

const file = 'src/ai/circuitChatAI.js';
let code = fs.readFileSync(file, 'utf8');

const t1 = `    } else if (mcuPin && mcuPin.startsWith('A')) {
      mcuPinSetups.add(\`  pinMode(\${mcuPin}, INPUT); // \${compId}\`);
// ── Main Chat AI class ────────────────────────────────────────────────────────`;

const t2 = `    } else if (mcuPin && mcuPin.startsWith('A')) {
      mcuPinSetups.add(\`  pinMode(\${mcuPin}, INPUT); // \${compId}\`);

// ── Main Chat AI class ────────────────────────────────────────────────────────`;

const t3 = `    } else if (mcuPin && mcuPin.startsWith('A')) {
      mcuPinSetups.add(\`  pinMode(\${mcuPin}, INPUT); // \${compId}\`);
 
 // ── Main Chat AI class ────────────────────────────────────────────────────────`;

const r1 = `    } else if (mcuPin && mcuPin.startsWith('A')) {
      mcuPinSetups.add(\`  pinMode(\${mcuPin}, INPUT); // \${compId}\`);
    }
  });

  mcuPinSetups.forEach(s => codeStr += s + '\\n');
  codeStr += \`}\\n\\nvoid loop() {\\n  // Auto-generated by TinkerAI Offline Engine\\n}\\n\`;
  payload.code = codeStr;
  
  out += '\\n\`\`\`cpp\\n' + codeStr + '\`\`\`\\n';
  out += \`\\n<!-- ACTION: \${JSON.stringify(payload)} -->\\n\`;
  out += \`<button class="ai-action-btn" onclick="window.executeAIAction(this.parentElement)">🚀 Generate Circuit</button>\\n\`;

  return out;
}

// ── Main Chat AI class ────────────────────────────────────────────────────────`;

let matched = false;
[t1, t2, t3].forEach(t => {
    if (code.includes(t)) { code = code.replace(t, r1); matched = true; }
    else if (code.includes(t.replace(/\n/g, '\r\n'))) { code = code.replace(t.replace(/\n/g, '\r\n'), r1.replace(/\n/g, '\r\n')); matched = true; }
});

if (!matched) {
    console.error("Not found! Here is the code snippet around line 1204:");
    const lines = code.split('\n');
    console.error(lines.slice(1200, 1210).join('\n'));
    process.exit(1);
}

fs.writeFileSync(file, code, 'utf8');
console.log("Restored successfully");
